name: Build release

on: [push, pull_request]

permissions: {}

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, windows-2022, macos-13]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install pkgconf
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        id: msys2
        with:
          msystem: ucrt64
          install: mingw-w64-ucrt-x86_64-pkgconf

      - name: Put pkgconf on PATH
        if: runner.os == 'Windows'
        run: Add-Content $env:GITHUB_PATH "${{ steps.msys2.outputs.msys2-location }}\ucrt64\bin"

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.0
        env:
          # Configure cibuildwheel on Linux to split the architectures
          # between the x86_64 and Arm64 runners.
          CIBW_ARCHS_LINUX: ${{ runner.arch == 'X64' && 'x86_64' || 'aarch64 armv7l' }}

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}
          path: wheelhouse/*.whl
          if-no-files-found: error

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  upload_pypi:
    name: Upload to PyPI
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v4
        with:
          # unpacks all CIBW artifacts into dist/
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
